import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'quick-start',
      label: 'Quick Start',
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: {
        type: 'doc',
        id: 'core-concepts/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'core-concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        title: 'Interactive Tutorials',
        description: 'Learn by building real VR experiences with step-by-step guides.',
        slug: '/tutorials',
      },
      items: [
        'tutorials/hello-vr-world',
        // More tutorials will be added here
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        title: 'Component Reference',
        description: 'Complete documentation for all Unity components available in the inspector.',
        slug: '/components',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      link: {
        type: 'generated-index',
        title: 'Scripting Guide',
        description: 'Learn to write MonoBehavior scripts for interactive behaviors.',
        slug: '/scripting',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'scripting',
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        title: 'Example Projects',
        description: 'Complete example projects with source code.',
        slug: '/examples',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Complete API documentation for developers.',
        slug: '/api',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

export default sidebars;